addReviewers: true
addAssignees: author
numberOfReviewers: 0
useReviewGroups: true

reviewGroups:
  cortex:
    - reviewerA
    - reviewerB
    - reviewerC

useAssigneeGroups: false
filterLabels:
  exclude:
    - wip
