name: 'Pull Request title rules'
on:
  pull_request:
    # branches-ignore: [master, main]
    types: [opened, edited, synchronize, reopened]

jobs:
  check-namming:
    runs-on: ubuntu-latest
    steps:
      - uses: deepakputhraya/action-pr-title@master
        with:
          regex: '^(revert: )?(build|chore|docs|feat|fix|perf|refactor|style|test)(\(.*\))?: .{1,50}' # Regex the title should match.
          github_token: ${{ secrets.GITHUB_TOKEN }}
